[package]
name = "gtk_rust_headerbar_example"
version = "0.0.0"
authors = ["Francisco Gómez <espectalll123@kydara.com>"]

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk.git"
features = ["3.10"]
